import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./main.style.css";
import { DataProvider } from "./DataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DataProvider>
      <html lang="en" className="scroll-smooth" data-scroll-behavior="smooth">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased home`}
        >
          {children}
        </body>
      </html>
    </DataProvider>
  );
}
