import type { Metadata } from "next";
import UserNavBar from "./component/UserNavBar";

export const metadata: Metadata = {
  title: "user",
  description: "Generated by create next app",
};

export default async function UserLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ username: string; id: string }>;
}>) {
  const { username } = await params;
  return (
    <div className={`antialiased`}>
      <UserNavBar username={username} />
      {children}
    </div>
  );
}
