import type { Metadata } from "next";

import NavBar from "./components/NavBar";
import Watch from "./components/Watch";

export const metadata: Metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` antialiased bg-slate-800`}>
      <NavBar />
      <Watch />
      {children}
    </div>
  );
}
